### ISSUE TITLE
[Bug] Equip stroe got status code 307

### ISSUE THREAD

**Issue by tinghaolai** [JDWorkoutApp/jd_workout_golang#80]

**Comment by tinghaolai** [comment]
先等 sentry 完成再修這邊

**Comment by johnson-724** [comment]
我測試正常看有沒有可能在 url path 最後多了 / 
gin 最後多加 / 會 307 重定向

**Comment by tinghaolai** [comment]
痾 好 我這邊處理

**Comment by johnson-724** [comment]
測試應該用 postman 等軟體會出現 301 or 307 的跳轉不過功能都正常
之後討論後端是不是要統一處理

**Comment by tinghaolai** [comment]
kk

**Comment by tinghaolai** [comment]
稍微看了一下
flutter 收到 307 後不會自動重打
是有辦法實做重打的機制
但先沒這打算

後端的話也可以規定2件事
1. 結尾統一有或沒有 slash /
2. api 文件也要一樣

可以之後再討論
目前我加上 slash 後是可以正常打的
所以先 close
